using System;
using System.Collections.Generic;

namespace PLLauncher.Services;

public class LocalizationService
{
    public static LocalizationService Instance { get; } = new();

    public event EventHandler? LanguageChanged;

    private string _language = "en-US";

    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
    {
        ["en-US"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["confirm.title"] = "Are you sure?",
            ["confirm.yes"] = "Yes",
            ["confirm.cancel"] = "Cancel",
            ["confirm.antisleep"] = "Keep the PC awake by moving the mouse? It stops when you move the mouse yourself.",
            ["confirm.shutdown"] = "Schedule shutdown in 1 hour?",
            ["confirm.lock"] = "Lock this PC now?",
            ["nav.dashboard"] = "Dashboard",
            ["nav.keybinds"] = "Keybinds",
            ["nav.tasks"] = "Tasks",
            ["nav.timelimits"] = "Time Limits",
            ["nav.scheduler"] = "Scheduler",
            ["nav.setups"] = "Setups",
            ["nav.pomodoro"] = "Pomodoro",
            ["nav.appusage"] = "App Usage",
            ["nav.settings"] = "Settings",
            ["settings.title"] = "Settings",
            ["settings.subtitle"] = "Configure PLLauncher preferences",
            ["settings.general"] = "General",
            ["settings.appearance"] = "Appearance",
            ["settings.performance"] = "Performance",
            ["settings.data"] = "Data Management",
            ["settings.language"] = "Language",
            ["settings.save"] = "Save Settings",
            ["settings.saved"] = "Settings saved successfully!",
            ["settings.unsaved"] = "You have unsaved changes",
            ["settings.discard"] = "Discard",
            ["lang.en"] = "English",
            ["lang.ru"] = "Russian",
            ["lang.zh"] = "Chinese (Simplified)",
            ["lang.es"] = "Spanish",
            ["settings.language_desc"] = "Applies after you save settings",
            ["settings.startup_label"] = "Launch on Startup",
            ["settings.startup_desc"] = "Start PLLauncher when Windows starts",
            ["settings.tray_label"] = "Minimize to System Tray",
            ["settings.tray_desc"] = "Keep running in background",
            ["settings.notifications_label"] = "Show Notifications",
            ["settings.notifications_desc"] = "Display Windows notifications",
            ["settings.darkmode_label"] = "Dark Mode",
            ["settings.darkmode_desc"] = "Use dark theme (turn off for light theme)",
            ["settings.animations_label"] = "Enable Animations",
            ["settings.animations_desc"] = "Smooth transitions and effects",
            ["settings.performance_label"] = "Performance Mode",
            ["settings.performance_desc"] = "Reduce background CPU usage",
            ["settings.warning_label"] = "Task Warning Time (min)",
            ["settings.warning_desc"] = "0 = no warning, else minutes before task to show popup",
            ["settings.cooldown_label"] = "Time Limit Cooldown (hours)",
            ["settings.cooldown_desc"] = "0 = instant unlock, else hours apps stay locked",
            ["settings.export_label"] = "Export Configuration",
            ["settings.export_desc"] = "Save all data to JSON",
            ["settings.import_label"] = "Import Configuration",
            ["settings.import_desc"] = "Restore from exported file",
            ["settings.reset_label"] = "Reset All Data",
            ["settings.reset_desc"] = "Delete everything permanently",
            ["dashboard.subtitle"] = "Here's your productivity overview",
            ["dashboard.active_hotkeys"] = "Active Hotkeys",
            ["dashboard.active_tasks"] = "Active Tasks",
            ["dashboard.time_limits"] = "Time Limits",
            ["dashboard.schedules"] = "Schedules",
            ["dashboard.quick_actions"] = "Quick Actions",
            ["dashboard.anti_sleep"] = "Anti-Sleep",
            ["dashboard.shutdown_1h"] = "Shutdown 1h",
            ["dashboard.lock_pc"] = "Lock PC",
            ["dashboard.system_status"] = "System Status",
            ["dashboard.system_status_ok"] = "All systems operational",
            ["dashboard.greeting_morning"] = "Good morning",
            ["dashboard.greeting_afternoon"] = "Good afternoon",
            ["dashboard.greeting_evening"] = "Good evening",
            ["dashboard.greeting_night"] = "Good night",
        },
        ["ru-RU"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["confirm.title"] = "Вы уверены?",
            ["confirm.yes"] = "Да",
            ["confirm.cancel"] = "Отмена",
            ["confirm.antisleep"] = "Не давать ПК заснуть, двигая мышь? Режим остановится, когда вы сами подвинете мышь.",
            ["confirm.shutdown"] = "Запланировать выключение через 1 час?",
            ["confirm.lock"] = "Заблокировать этот ПК сейчас?",
            ["nav.dashboard"] = "Панель",
            ["nav.keybinds"] = "Горячие клавиши",
            ["nav.tasks"] = "Задачи",
            ["nav.timelimits"] = "Лимиты времени",
            ["nav.scheduler"] = "Планировщик",
            ["nav.setups"] = "Наборы",
            ["nav.pomodoro"] = "Помодоро",
            ["nav.appusage"] = "Использование",
            ["nav.settings"] = "Настройки",
            ["settings.title"] = "Настройки",
            ["settings.subtitle"] = "Настройка PLLauncher",
            ["settings.general"] = "Общие",
            ["settings.appearance"] = "Внешний вид",
            ["settings.performance"] = "Производительность",
            ["settings.data"] = "Данные",
            ["settings.language"] = "Язык",
            ["settings.save"] = "Сохранить",
            ["settings.saved"] = "Настройки сохранены!",
            ["settings.unsaved"] = "Есть несохранённые изменения",
            ["settings.discard"] = "Отменить",
            ["lang.en"] = "Английский",
            ["lang.ru"] = "Русский",
            ["lang.zh"] = "Китайский (упрощённый)",
            ["lang.es"] = "Испанский",
            ["settings.language_desc"] = "Применяется после сохранения",
            ["settings.startup_label"] = "Запуск при старте Windows",
            ["settings.startup_desc"] = "Запускать PLLauncher при загрузке Windows",
            ["settings.tray_label"] = "Сворачивать в трей",
            ["settings.tray_desc"] = "Оставаться в фоне",
            ["settings.notifications_label"] = "Показывать уведомления",
            ["settings.notifications_desc"] = "Показывать уведомления Windows",
            ["settings.darkmode_label"] = "Тёмная тема",
            ["settings.darkmode_desc"] = "Использовать тёмную тему",
            ["settings.animations_label"] = "Анимация",
            ["settings.animations_desc"] = "Плавные переходы и эффекты",
            ["settings.performance_label"] = "Режим производительности",
            ["settings.performance_desc"] = "Снизить нагрузку на ЦП",
            ["settings.warning_label"] = "Время предупреждения (мин)",
            ["settings.warning_desc"] = "0 = без предупреждения; за сколько минут показать напоминание",
            ["settings.cooldown_label"] = "Ожидание после снятия (часы)",
            ["settings.cooldown_desc"] = "0 = мгновенная разблокировка; часы блокировки приложений",
            ["settings.export_label"] = "Экспорт настроек",
            ["settings.export_desc"] = "Сохранить все данные в JSON",
            ["settings.import_label"] = "Импорт настроек",
            ["settings.import_desc"] = "Восстановить из файла",
            ["settings.reset_label"] = "Сбросить все данные",
            ["settings.reset_desc"] = "Удалить всё навсегда",
            ["dashboard.subtitle"] = "Обзор продуктивности",
            ["dashboard.active_hotkeys"] = "Активные горячие клавиши",
            ["dashboard.active_tasks"] = "Активные задачи",
            ["dashboard.time_limits"] = "Лимиты времени",
            ["dashboard.schedules"] = "Планы",
            ["dashboard.quick_actions"] = "Быстрые действия",
            ["dashboard.anti_sleep"] = "Блокировка сна",
            ["dashboard.shutdown_1h"] = "Выкл. через 1ч",
            ["dashboard.lock_pc"] = "Заблокировать ПК",
            ["dashboard.system_status"] = "Состояние системы",
            ["dashboard.system_status_ok"] = "Всё работает",
            ["dashboard.greeting_morning"] = "Доброе утро",
            ["dashboard.greeting_afternoon"] = "Добрый день",
            ["dashboard.greeting_evening"] = "Добрый вечер",
            ["dashboard.greeting_night"] = "Доброй ночи",
        },
        ["zh-CN"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["confirm.title"] = "确定吗？",
            ["confirm.yes"] = "是",
            ["confirm.cancel"] = "取消",
            ["confirm.antisleep"] = "通过移动鼠标防止电脑休眠？当您自己移动鼠标时会停止。",
            ["confirm.shutdown"] = "计划在 1 小时后关机？",
            ["confirm.lock"] = "立即锁定此电脑？",
            ["nav.dashboard"] = "仪表板",
            ["nav.keybinds"] = "快捷键",
            ["nav.tasks"] = "任务",
            ["nav.timelimits"] = "时间限制",
            ["nav.scheduler"] = "计划",
            ["nav.setups"] = "启动组",
            ["nav.pomodoro"] = "番茄钟",
            ["nav.appusage"] = "应用使用",
            ["nav.settings"] = "设置",
            ["settings.title"] = "设置",
            ["settings.subtitle"] = "配置 PLLauncher",
            ["settings.general"] = "常规",
            ["settings.appearance"] = "外观",
            ["settings.performance"] = "性能",
            ["settings.data"] = "数据管理",
            ["settings.language"] = "语言",
            ["settings.save"] = "保存设置",
            ["settings.saved"] = "设置已保存！",
            ["settings.unsaved"] = "有未保存的更改",
            ["settings.discard"] = "放弃",
            ["lang.en"] = "英语",
            ["lang.ru"] = "俄语",
            ["lang.zh"] = "简体中文",
            ["lang.es"] = "西班牙语",
            ["settings.language_desc"] = "保存后生效",
            ["settings.startup_label"] = "开机启动",
            ["settings.startup_desc"] = "Windows 启动时运行 PLLauncher",
            ["settings.tray_label"] = "最小化到系统托盘",
            ["settings.tray_desc"] = "在后台继续运行",
            ["settings.notifications_label"] = "显示通知",
            ["settings.notifications_desc"] = "显示 Windows 通知",
            ["settings.darkmode_label"] = "深色模式",
            ["settings.darkmode_desc"] = "使用深色主题（关闭为浅色主题）",
            ["settings.animations_label"] = "启用动画",
            ["settings.animations_desc"] = "平滑过渡和效果",
            ["settings.performance_label"] = "性能模式",
            ["settings.performance_desc"] = "减少后台 CPU 使用",
            ["settings.warning_label"] = "任务警告时间（分钟）",
            ["settings.warning_desc"] = "0 = 不警告，否则任务前多少分钟弹出提醒",
            ["settings.cooldown_label"] = "时间限制冷却（小时）",
            ["settings.cooldown_desc"] = "0 = 立即解锁，否则应用锁定小时数",
            ["settings.export_label"] = "导出配置",
            ["settings.export_desc"] = "将所有数据保存为 JSON",
            ["settings.import_label"] = "导入配置",
            ["settings.import_desc"] = "从导出文件恢复",
            ["settings.reset_label"] = "重置所有数据",
            ["settings.reset_desc"] = "永久删除所有数据",
            ["dashboard.subtitle"] = "您的生产力概览",
            ["dashboard.active_hotkeys"] = "活动快捷键",
            ["dashboard.active_tasks"] = "活动任务",
            ["dashboard.time_limits"] = "时间限制",
            ["dashboard.schedules"] = "计划",
            ["dashboard.quick_actions"] = "快速操作",
            ["dashboard.anti_sleep"] = "防睡眠",
            ["dashboard.shutdown_1h"] = "1小时后关机",
            ["dashboard.lock_pc"] = "锁定电脑",
            ["dashboard.system_status"] = "系统状态",
            ["dashboard.system_status_ok"] = "一切正常",
            ["dashboard.greeting_morning"] = "早上好",
            ["dashboard.greeting_afternoon"] = "下午好",
            ["dashboard.greeting_evening"] = "晚上好",
            ["dashboard.greeting_night"] = "晚安",
        },
        ["es-ES"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["confirm.title"] = "¿Está seguro?",
            ["confirm.yes"] = "Sí",
            ["confirm.cancel"] = "Cancelar",
            ["confirm.antisleep"] = "¿Mantener el PC despierto moviendo el ratón? Se detiene cuando usted lo mueva.",
            ["confirm.shutdown"] = "¿Programar apagado en 1 hora?",
            ["confirm.lock"] = "¿Bloquear este PC ahora?",
            ["nav.dashboard"] = "Panel",
            ["nav.keybinds"] = "Atajos",
            ["nav.tasks"] = "Tareas",
            ["nav.timelimits"] = "Límites",
            ["nav.scheduler"] = "Programador",
            ["nav.setups"] = "Grupos",
            ["nav.pomodoro"] = "Pomodoro",
            ["nav.appusage"] = "Uso de apps",
            ["nav.settings"] = "Ajustes",
            ["settings.title"] = "Ajustes",
            ["settings.subtitle"] = "Configurar PLLauncher",
            ["settings.general"] = "General",
            ["settings.appearance"] = "Apariencia",
            ["settings.performance"] = "Rendimiento",
            ["settings.data"] = "Datos",
            ["settings.language"] = "Idioma",
            ["settings.save"] = "Guardar",
            ["settings.saved"] = "¡Ajustes guardados!",
            ["settings.unsaved"] = "Hay cambios sin guardar",
            ["settings.discard"] = "Descartar",
            ["lang.en"] = "Inglés",
            ["lang.ru"] = "Ruso",
            ["lang.zh"] = "Chino (simplificado)",
            ["lang.es"] = "Español",
            ["settings.language_desc"] = "Se aplica después de guardar",
            ["settings.startup_label"] = "Iniciar con Windows",
            ["settings.startup_desc"] = "Iniciar PLLauncher al arrancar Windows",
            ["settings.tray_label"] = "Minimizar a la bandeja",
            ["settings.tray_desc"] = "Seguir ejecutándose en segundo plano",
            ["settings.notifications_label"] = "Mostrar notificaciones",
            ["settings.notifications_desc"] = "Mostrar notificaciones de Windows",
            ["settings.darkmode_label"] = "Modo oscuro",
            ["settings.darkmode_desc"] = "Usar tema oscuro (desactivar para tema claro)",
            ["settings.animations_label"] = "Activar animaciones",
            ["settings.animations_desc"] = "Transiciones y efectos suaves",
            ["settings.performance_label"] = "Modo rendimiento",
            ["settings.performance_desc"] = "Reducir uso de CPU en segundo plano",
            ["settings.warning_label"] = "Tiempo de aviso (min)",
            ["settings.warning_desc"] = "0 = sin aviso; minutos antes de la tarea para mostrar ventana",
            ["settings.cooldown_label"] = "Enfriamiento de límites (horas)",
            ["settings.cooldown_desc"] = "0 = desbloqueo instantáneo; horas de bloqueo de apps",
            ["settings.export_label"] = "Exportar configuración",
            ["settings.export_desc"] = "Guardar todos los datos en JSON",
            ["settings.import_label"] = "Importar configuración",
            ["settings.import_desc"] = "Restaurar desde archivo exportado",
            ["settings.reset_label"] = "Restablecer todo",
            ["settings.reset_desc"] = "Eliminar todo permanentemente",
            ["dashboard.subtitle"] = "Resumen de productividad",
            ["dashboard.active_hotkeys"] = "Atajos activos",
            ["dashboard.active_tasks"] = "Tareas activas",
            ["dashboard.time_limits"] = "Límites de tiempo",
            ["dashboard.schedules"] = "Programaciones",
            ["dashboard.quick_actions"] = "Acciones rápidas",
            ["dashboard.anti_sleep"] = "Anti-sueño",
            ["dashboard.shutdown_1h"] = "Apagar en 1h",
            ["dashboard.lock_pc"] = "Bloquear PC",
            ["dashboard.system_status"] = "Estado del sistema",
            ["dashboard.system_status_ok"] = "Todo operativo",
            ["dashboard.greeting_morning"] = "Buenos días",
            ["dashboard.greeting_afternoon"] = "Buenas tardes",
            ["dashboard.greeting_evening"] = "Buenas noches",
            ["dashboard.greeting_night"] = "Buenas noches",
        },
    };

    public string CurrentLanguage
    {
        get => _language;
        set
        {
            if (_language == value) return;
            _language = NormalizeLanguage(value);
            LanguageChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public static string NormalizeLanguage(string code) => code switch
    {
        "ru" or "ru-RU" => "ru-RU",
        "zh" or "zh-CN" => "zh-CN",
        "es" or "es-ES" => "es-ES",
        _ => "en-US"
    };

    public string Get(string key)
    {
        if (Strings.TryGetValue(_language, out var lang) && lang.TryGetValue(key, out var value))
            return value;
        if (Strings["en-US"].TryGetValue(key, out var fallback))
            return fallback;
        return key;
    }

    public void LoadFromSettings(string? languageCode)
        => CurrentLanguage = NormalizeLanguage(languageCode ?? "en-US");
}
